version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COOLIFY_RESOURCE_UUID}.rule=Host(`${COOLIFY_FQDN}`)"
      - "traefik.http.routers.${COOLIFY_RESOURCE_UUID}.entrypoints=https"
      - "traefik.http.routers.${COOLIFY_RESOURCE_UUID}.tls=true"
      - "traefik.http.routers.${COOLIFY_RESOURCE_UUID}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COOLIFY_RESOURCE_UUID}.loadbalancer.server.port=80"

networks:
  coolify:
    external: true